### ISSUE TITLE
[Design] 내 정보 조회 모달 창 만들기

### ISSUE THREAD

**Issue by castlewook99** [SV-Winter-BootCamp-Team-C/frontend#44]
**구현 할 기능에 대한 설명**
내 정보 조회 모달 창 만들기

**TODO List**
- [ ] 내 정보 조회 page와 common 연결
- [ ] Profile 누르면 내 정보 조회 모달 창 구현
- [ ] Profile 누르면 바탕은 회색으로 구현

**참고 자료**
디자인 컨셉과 관련된 추가 정보나 스크린샷 등이 있다면 첨부해 주세요.
![내 정보 조회](https://github.com/SV-Winter-BootCamp-Team-C/frontend/assets/154862467/731432e6-6879-461e-a81f-86584f2ace83)
